spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mkrew
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: mkrew.kontakt@gmail.com
    password: mkrew.sda
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


info:
  app:
    profile: ${spring.profiles.active}
  serverInfo:
    os: ${os.name}
  user:
    timeZone: ${user.timezone}
    country: ${user.country}
  metrics:

management:
  endpoints:
    web:
      exposure:
        include: '*'

springfox:
  documentation:
    swagger-ui:
      enabled: true